spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:17.0:///test
    username: test
    password: test
  temporal:
    namespace: default
    connection:
      target: localhost:7233
    test-server:
      enabled: true
